### ISSUE TITLE
Precision issues in geometric_classification causing misclassification

### ISSUE THREAD

**Issue by agcopenhaver** [ClarkCGA/UDef-ARP#31]
https://github.com/ClarkCGA/UDef-ARP/blob/96013b8138dfde808f764084a6c2d8ab85906d15/vulnerability_map.py#L108-L124

In this code block, precision issues can lead to situations where the class boundaries derived in `risk_class=np.multiply(UL,x)` do not equal LL or UL.

For example, in `print(risk_class[28][1] == LL)` should , I believe, always evaluate to True, as the lower limit of the highest risk class should be equivalent to the spatial resolution of the input, but using the data shared in #29, `risk_class[28][1] ` actually equals `100.00000000000016`

I think an acceptable short term fix would just be to explicity set the upper and lower limits using the spatial resolution and the NRT instead of relying on ` x= np.power(r, class_array)` and `risk_class=np.multiply(UL,x) ` to return the exact values we need. eg:

```
risk_class[n_classes-1][1] = LL
risk_class[0][0] = NRT
```

I'll open up a PR to do that

**Comment by YaoTingYao** [comment]
Hi @agcopenhaver, thank you for identifying the precision issue. I agree that risk_class[n_classes-1][1] can experience precision problems with the default float64 datatype. Also, since risk_class[0][0] will naturally be set to NRT due to x[0][0] being 1, it might be cleaner to remove the explicit assignment risk_class[0][0] = NRT. What do you think?

**Comment by YaoTingYao** [comment]
Since the statement ```risk_class[0][0] = NRT``` would not cause any memory or performance issues and helps users understand the arrangement of risk_class, the PR is good to go.
