### ISSUE TITLE
An error occurred during processing: Maximum allowed size exceeded. Error when calculating the NRT for calibration. 

### ISSUE THREAD

**Issue by neurojunior** [ClarkCGA/UDef-ARP#44]
I'm testing udef-arp and I'm getting an error when calculating the NRT for calibration.

I've tested it on several extensions, uint8, uint16, uint32, float and they all show this error:
![image](https://github.com/user-attachments/assets/bf9f6a38-61d3-4877-8062-ba5dae9c45df)

Could you help me, guide me, I am using Google Earth Engine to generate the data, it is an area of ​​interest of approximately 281,000 hectares in Brazil, images with a resolution of 30 meters.

**Comment by YaoTingYao** [comment]
Hi @neurojunior 

The computational limitations will depend on your local machine's memory and the size of the processing images. May I ask how much RAM your computer has? Based on the area of interest size and image resolution you provided, the computation should work fine. If you'd like, feel free to share your dataset for further testing.

The memory-optimized version of UDef-ARP is currently under testing. In the meantime, Clark CGA has released a free version of [TerrSet](https://github.com/ClarkCGA/TerrSet), which includes the same tool for the UDef-A procedure. TerrSet efficiently manages computations through optimized memory allocation, so you might find it useful to try.

**Comment by YaoTingYao** [comment]
Hi @neurojunior, I will close it for now. Please feel free to reopen it if the issue persists. Thank you!

**Comment by neurojunior** [comment]
I don't think it's a processing issue. My computer is a latest generation Ryzen 9, with 64GB of dedicated RAM and a 12GB dedicated GPU-video, focused on AI training.

We're waiting for the error to be resolved in the next updates. I've already deployed outside using chatgpt and gemini, and the error you pointed out was the first on the list. There is an incompatibility in the input aspect of Geotiff data, which you should address in the documentation. The tool only works well with the .terrset extension.

I know several developers who simply stopped using UDEF-ARP due to errors and inconsistencies. Unfortunately, it's not delivering what's in the community's best interest, as is happening with the carbon market, in terms of "transparency";

Thank you for your attention.

**Comment by YaoTingYao** [comment]
Hi @neurojunior, thank you for the feedback and for sharing your system specifications. The RAM and image size shouldn’t pose an issue for UDef-ARP, and the tool does support GeoTIFF formats as we addressed in documentation. To better pinpoint the cause of the error you’ve encountered, could you please provide your dataset for further test? With that, we’ll be able to run more targeted tests and assist  you with this issue.

**Comment by neurojunior** [comment]
Below is the data used that caused the error.

[Test_udef_arp_erros.zip](https://github.com/user-attachments/files/18189339/Test_udef_arp_erros.zip)

**Comment by tawoodard** [comment]
Hi,

I thought I'd take a look at this data in TerrSet's UDef-A, to see how it did.

I see why UDef-ARP is having trouble with it.

I'm using the data in the teste_2 folder.
There are some cells with a value of 1 in the Deforestation in the HRP image(Projeto_MT_DefoDuringHRP), which means that they should have been forest at time 1 and deforested at time 3, that have a value of 0 in the Distance from the Forest Edge image (edge_forest_t1_2009_clip_32bt).  If they are 0 distance from NonForest, it means that they were non-forest at time 1.  So how could they have become deforested during the HRP?  The data doesn't make sense.

Perhaps we need better error traps that look for this type of problem.  The error message that you get in TerrSet's UDef-A first happens when calculating the NRT and is "Cumulative proportion not reached because of mask.  Check that correct mask image was used."  But the user wouldn't realize that the mask used in HISTO, which was calculating the cumulative proportion, was a combination of the jurisdiction mask & the deforestation in the HRP.  So the user wouldn't know how to correct their problem.  I am guessing that UDef-ARP is also assuming that the data is correctly made, and the error message about maximum reached might be a catch-all for an untrapped error.  But I only looked at the TerrSet one.
***@***.***

If I continue on to try to calculate the output vulnerability in the CAL, I get an untrapped error (Unexpected Error Encountered), again, because there is a logical problem with the data.  I will need to add more protections for this.

Tammy

From: Neuro Salvador da Silva Junior ***@***.***>
Sent: Wednesday, December 18, 2024 5:12 PM
To: ClarkCGA/UDef-ARP ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXT] Re: [ClarkCGA/UDef-ARP] An error occurred during processing: Maximum allowed size exceeded. Error when calculating the NRT for calibration. (Issue #44)


Below is the data used that caused the error.

Test_udef_arp_erros.zip<https://github.com/user-attachments/files/18189339/Test_udef_arp_erros.zip>

-

**Comment by neurojunior** [comment]
@tawoodard I appreciate your attention and considerations;

I believe it was an error not to assign the "exclusion areas" classes that exist in the Jurisdiction. In Brazil, according to forestry legislation, we consider "approved deforestation" to be areas that were converted up to 07/22/2008. I will reassign and redo the tests. I am grateful for identifying this in the HRP data.

But I did the same as @tawoodard , I added the data in .rst in Terrset, with the UDEF-A tool and processed the same data without obtaining a memory error.

This memory error is an anachronistic error in a script, as if it were a warning error, it does not force the process so that the memory cannot handle it.

I appreciate your help, and I will continue to follow the solutions for this UDEF-ARP error.

Running in UDEF-A through Terrset is working, the same data I was able to obtain the NRT.

**Comment by YaoTingYao** [comment]
Hi @neurojunior 

It appears that the resolution of your images was set to 0.000269494585235856472 instead of 30. Setting the bin width to the integer part of the spatial resolution caused the histogram calculation to fail with a 'ValueError: Maximum allowed size exceeded.' I’ll update line 67 to resolve this issue.

However, please note that you will need to recreate your input images with the correct spatial resolution and recalculate the NRT value. Since the bin width will be much larger, the 0.995 index cumulative proportion might fall into a different bin than before. Using the proper spatial resolution is also vital importance for later phases.

Regarding error handling, the UDef-ARP currently uses str(e) for rapid exception generation, providing a brief, user-friendly error key message. However, in your case, a more detailed stack trace would be needed for effective debugging. As @tawoodard mentioned, we will enhance the error messages and include detection for input errors in future versions.

Thank you for your feedback. The UDef-ARP repository is open source. We invite everyone to review the code, submit pull requests, post issues, and share insights as contributors to improve the scripts. By working together, we can create a more robust tool for the best benefit of the entire community. Cheers!

**Comment by neurojunior** [comment]
@YaoTingYao Thank you once again for your response. The problem was really due to the fact that the Projection was in geographic format. It might be interesting information to include this in the documentation or even on GitHub in future updates. 

I used the SIRGAS 2000 21S projection, which is relevant to my region. It worked without the memory error.

Thank you very much for your attention. Good luck with your work!

Thank you to @tawoodard  for the guidance that was going unnoticed in the deforestation HRP.

As @YaoTingYao  commented, "By working together, we can create a more robust tool for the greater benefit of the entire community." I would like to add that together we are stronger!

Forward!
